name: Patch APK with ReVanced

on:
  workflow_dispatch:
    inputs:
      org:
        description: 'Developer org on APKMirror (e.g., tiktok-pte-ltd for TikTok)'
        required: true
        default: 'tiktok-pte-ltd'
      repo:
        description: 'App repo on APKMirror (e.g., tik-tok for TikTok)'
        required: true
        default: 'tik-tok'
      version:
        description: 'App version (e.g., 41.7.3; leave empty for latest)'
        required: false
        default: ''

jobs:
  patch-apk:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository (optional, if you need other files from your repo)
      - name: Checkout repository
        uses: actions/checkout@v4

      # Install Java (required for ReVanced CLI)
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Download APK using gh-apkmirror-dl action
      - name: Download APK from APKMirror
        id: download
        uses: Yakov5776/gh-apkmirror-dl@v1.3
        with:
          org: ${{ github.event.inputs.org }}
          repo: ${{ github.event.inputs.repo }}
          version: ${{ github.event.inputs.version }}
          bundle: false  # Download APK, not bundle
          filename: app.apk  # Output name

      # Verify download (optional, for safety)
      - name: Verify APK
        run: |
          APK_SIZE=$(stat -c%s app.apk)
          if [ "$APK_SIZE" -lt 10000000 ]; then
            echo "Error: Downloaded file too small ($APK_SIZE bytes), not a real APK."
            exit 1
          fi
          echo "APK downloaded successfully: $APK_SIZE bytes"

      # Download latest ReVanced CLI
      - name: Download ReVanced CLI
        run: |
          CLI_URL=$(curl -s https://api.github.com/repos/ReVanced/revanced-cli/releases/latest | jq -r '.assets[] | select(.name | endswith(".jar")) | .browser_download_url')
          curl -L "$CLI_URL" -o revanced-cli.jar

      # Download latest ReVanced patches from your repository
      - name: Download ReVanced Patches
        run: |
          PATCHES_URL=$(curl -s https://api.github.com/repos/krolchonok/revances_patches/releases/latest | jq -r '.assets[] | select(.name | endswith(".rvp")) | .browser_download_url')
          curl -L "$PATCHES_URL" -o patches.rvp

      # Patch APK using ReVanced CLI
      - name: Patch APK
        run: |
          java -jar revanced-cli.jar patch -f -p patches.rvp \
            --exclusive \
            -e "Downloads" \
            -e "SIM spoof" \
            -e "Fix Google login" \
            -e "Disable login requirement" \
            -e "Show seekbar" \
            app.apk

      # Upload patched APK as artifact
      - name: Upload Patched APK
        uses: actions/upload-artifact@v4
        with:
          name: patched-apk
          path: patched*.apk
