name: Patch APK with ReVanced

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'Прямая ссылка на APK (будет скачано в app.apk)'
        required: true
        default: ''

jobs:
  patch-apk:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Ensure tools
        run: |
          sudo apt-get update
          sudo apt-get install -y jq curl wget

      - name: Download APK with wget
        run: |
          if [ -z "${{ github.event.inputs.url }}" ]; then
            echo "Error: Не указана ссылка на APK (input 'url')."
            exit 1
          fi
          wget -L -O app.apk "${{ github.event.inputs.url }}"

      - name: Verify APK
        run: |
          APK_SIZE=$(stat -c%s app.apk)
          if [ "$APK_SIZE" -lt 10000000 ]; then
            echo "Error: Downloaded file too small ($APK_SIZE bytes), not a real APK."
            exit 1
          fi
          echo "APK downloaded successfully: $APK_SIZE bytes"

      - name: Download ReVanced CLI
        run: |
          CLI_URL=$(curl -s https://api.github.com/repos/ReVanced/revanced-cli/releases/latest | jq -r '.assets[] | select(.name | endswith(".jar")) | .browser_download_url')
          curl -L "$CLI_URL" -o revanced-cli.jar

      - name: Download ReVanced Patches
        run: |
          PATCHES_URL=$(curl -s https://api.github.com/repos/krolchonok/revanced-patches/releases/latest | jq -r '.assets[] | select(.name | endswith(".rvp")) | .browser_download_url')
          curl -L "$PATCHES_URL" -o patches.rvp

      - name: Patch APK
        run: |
          java -jar revanced-cli.jar patch -f -p patches.rvp \
            --exclusive \
            -e "Downloads" \
            -e "SIM spoof" \
            -e "Fix Google login" \
            -e "Disable login requirement" \
            -e "Show seekbar" \
            app.apk

      - name: Rename output
        run: mv -v app-patched.apk titkok-app.apk

      - name: Upload Patched APK
        uses: actions/upload-artifact@v4
        with:
          name: titkok-app
          path: titkok-app.apk

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: auto-${{ github.run_number }}-${{ github.run_id }}
          name: "TikTok Patched APK - Auto Release ${{ github.run_number }}"
          body: |
            🚀 Автоматически созданный релиз с пропатченным TikTok APK
            
            **Информация о релизе:**
            - Исходный APK: ${{ github.event.inputs.url }}
            - Дата создания: ${{ github.event.head_commit.timestamp }}
            - Workflow Run: ${{ github.run_number }}
            - Commit: ${{ github.sha }}
            
            **Установка:**
            1. Скачайте `titkok-app.apk`
            2. Разрешите установку из неизвестных источников
            3. Установите APK файл
          files: titkok-app.apk
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

